# Generated by Django 5.0.1 on 2024-01-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='tags',
        ),
        migrations.AddField(
            model_name='about',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
