# Generated by Django 5.0.1 on 2024-01-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_about_tags_about_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.about'),
            preserve_default=False,
        ),
    ]
