# Generated by Django 5.0.1 on 2024-01-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_testimonial_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=212)),
                ('des', models.TextField()),
            ],
        ),
    ]
