# Generated by Django 5.0.1 on 2024-01-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_ours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=212)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('crt', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=212)),
                ('des', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
