# Generated by Django 5.0.1 on 2024-01-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
